version: "3.5"
services:
  pps-mongo:
    image: mongo:5.0
    container_name: "mongo-query-filter"
    ports:
      - 27117:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: lok
      
  pps-mongo-express:
    image: mongo-express
    container_name: "mongo_express-query-filter"
    restart: on-failure
    ports:
      - 27118:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: lok
      ME_CONFIG_MONGODB_SERVER: pps-mongo      