version: '3.1'
services:
  mysql-dev:
    image: "mysql:latest"
    container_name: "mysql-dev"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: tukan